# Generated by Django 2.0.9 on 2018-12-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transact',
            fields=[
                ('TransId', models.AutoField(primary_key=True, serialize=False)),
                ('Time', models.DateTimeField()),
                ('Amount', models.IntegerField()),
                ('Recipient', models.CharField(max_length=200)),
            ],
        ),
    ]
