# Generated by Django 2.1.2 on 2018-11-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('couponId', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(max_length=150)),
            ],
        ),
    ]
