# Generated by Django 2.1.2 on 2018-11-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0002_auto_20181109_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderId', models.AutoField(primary_key=True, serialize=False)),
                ('orderName', models.CharField(max_length=150)),
                ('amount', models.FloatField()),
                ('valid', models.BooleanField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='coupons',
            name='addTime',
            field=models.DateTimeField(),
        ),
    ]
