# Generated by Django 2.0.9 on 2018-11-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0003_auto_20181110_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('postId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('addTime', models.DateTimeField()),
            ],
        ),
    ]
