# Generated by Django 2.0.9 on 2018-12-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0004_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='slug',
            field=models.SlugField(blank=True, max_length=5),
        ),
    ]
