# Generated by Django 2.1.2 on 2018-11-11 22:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermess', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponsbought',
            name='boughtTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 11, 22, 11, 23, 928786)),
        ),
        migrations.AlterField(
            model_name='couponsbought',
            name='couponId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mess.Coupons'),
        ),
    ]
