# Generated by Django 2.1.2 on 2018-11-11 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermess', '0002_auto_20181111_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponsbought',
            name='email',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='couponsbought',
            name='boughtTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 11, 22, 21, 42, 9531)),
        ),
    ]
