# Generated by Django 2.1.2 on 2018-11-12 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermess', '0003_auto_20181111_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponsbought',
            name='boughtTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 12, 1, 0, 40, 250457)),
        ),
    ]
