# Generated by Django 2.1.2 on 2018-11-13 02:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermess', '0005_auto_20181112_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponsbought',
            name='boughtTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 13, 2, 39, 0, 978018)),
        ),
    ]
