# Generated by Django 2.0.9 on 2018-11-14 11:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('usermess', '0007_auto_20181113_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponsbought',
            name='boughtTime',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 14, 11, 2, 47, 143476, tzinfo=utc)),
        ),
    ]
