# Generated by Django 2.0.9 on 2018-11-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermess', '0008_auto_20181114_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('reviewId', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('user', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='couponsbought',
            name='boughtTime',
            field=models.DateTimeField(),
        ),
    ]
