# Generated by Django 2.0.9 on 2018-11-17 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0004_posts'),
        ('usermess', '0009_auto_20181116_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersBought',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boughtTime', models.DateTimeField()),
                ('delTime', models.DateTimeField()),
                ('email', models.CharField(max_length=150)),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mess.Orders')),
            ],
        ),
    ]
