# Generated by Django 2.0.9 on 2018-12-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0003_auto_20181212_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='PayId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
