# Generated by Django 2.1.3 on 2018-11-11 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='roomname',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
