# Generated by Django 2.1.3 on 2018-11-12 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_rec_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='rec_name',
        ),
    ]
