# Generated by Django 2.1.3 on 2018-11-12 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_message_rec_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='rec_name',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
