# Generated by Django 2.0.9 on 2018-12-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_profile_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='card_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
