# Generated by Django 2.1.2 on 2018-10-14 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_ID', models.CharField(max_length=100)),
                ('week_money', models.CharField(max_length=100)),
                ('month_money', models.CharField(max_length=100)),
            ],
        ),
    ]
