# Generated by Django 2.1.2 on 2018-10-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycleshare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='month_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cycle',
            name='week_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
