# Generated by Django 2.1.2 on 2018-10-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycleshare', '0002_auto_20181014_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='month_date',
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='week_date',
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='week_money',
        ),
        migrations.AddField(
            model_name='cycle',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cycle',
            name='month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cycle',
            name='week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cycle',
            name='week_sub',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cycle',
            name='month_money',
            field=models.FloatField(null=True),
        ),
    ]
