# Generated by Django 2.1.2 on 2018-10-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycleshare', '0003_auto_20181027_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycle',
            old_name='student_name',
            new_name='fullname',
        ),
    ]
