# Generated by Django 2.1.2 on 2018-10-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycleshare', '0004_auto_20181027_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cycle',
            old_name='month_money',
            new_name='month_sub',
        ),
    ]
