# Generated by Django 2.1.2 on 2018-11-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycleshare', '0005_auto_20181027_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='month',
        ),
        migrations.AddField(
            model_name='cycle',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
