# Generated by Django 2.1.2 on 2018-11-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycleshare', '0006_auto_20181107_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='avalability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type1', models.IntegerField()),
                ('type2', models.IntegerField()),
                ('type3', models.IntegerField()),
            ],
        ),
    ]
