# Generated by Django 2.1.2 on 2018-11-07 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycleshare', '0008_auto_20181107_1415'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='q',
            new_name='available',
        ),
    ]
