# Generated by Django 2.0.9 on 2018-12-12 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycleshare', '0012_cycle_toprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycle',
            name='toprofile',
        ),
    ]
