# Generated by Django 2.0.9 on 2018-12-12 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cycleshare', '0014_cycle_toprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='toprofile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dashboard.Profile'),
        ),
    ]
