# Generated by Django 2.1.2 on 2018-11-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarian',
            name='due',
            field=models.IntegerField(null=True),
        ),
    ]
