# Generated by Django 2.1.2 on 2018-11-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0003_auto_20181113_1904'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='librarian',
            new_name='librarian1',
        ),
    ]
