# Generated by Django 2.1.2 on 2018-11-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0005_auto_20181113_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='libdb',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('student_ID', models.CharField(max_length=100)),
                ('book_ID', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('due', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='libfinal',
        ),
    ]
