# Generated by Django 2.1.2 on 2018-11-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0006_auto_20181113_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libdb',
            name='id',
        ),
        migrations.AlterField(
            model_name='libdb',
            name='book_ID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
