# Generated by Django 2.1.2 on 2018-11-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0007_auto_20181113_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='dblib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_ID', models.CharField(max_length=100)),
                ('book_ID', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('due', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='libdb',
        ),
    ]
