# Generated by Django 2.1.2 on 2018-11-13 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0008_auto_20181113_1927'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dblib',
            new_name='librarian',
        ),
    ]
