# Generated by Django 2.1.2 on 2018-11-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='days_left',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='due',
            field=models.IntegerField(),
        ),
    ]
