# Generated by Django 2.0.9 on 2018-12-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payway', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paywaylog',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='paywaylog',
            name='flag',
        ),
    ]
